import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '../components/Hero.jsx'
import Header from '../components/Header.jsx'
import About from '@/components/About.jsx'
import Work from '@/components/Work.jsx'
import Reviews from '@/components/Reviews.jsx'
import Contact from '@/components/Contact.jsx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Hero/>
      <About/>
      <Work/>
      <Contact/>
    </>
  )
}
